import Head from 'next/head'
import Link from 'next/link'
import styles from '../../styles/Home.module.css'
import getOnePost from '../../utils/getOnePost'
import Container from 'react-bootstrap/Container'
import Col from 'react-bootstrap/Col'
import Row from 'react-bootstrap/Row'
import Image from 'react-bootstrap/Image'

export async function getServerSideProps({ params }) {
  const post = await getOnePost(params.id);
  return {
    props: {
      post: post,
    }
  };
}

export default function Home(props) {
  const post = props.post;


  return (
    <div className={styles.container}>
      <Head>
        <title>{post.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <script src="https://upload-widget.cloudinary.com/global/all.js" type="text/javascript"></script>
      <main className={styles.main}>
      <p><Link href="/posts"><a>&larr; Back</a></Link></p>
        <h1 className={styles.title}>
          {post.title}
        </h1>

            <Container>
                <Row className="justify-content-md-center">
                    <Col>
                        <Image
                            src={post.imgUrl}
                            alt="Uploaded Image"
                            rounded
                            fluid
                            className="mx-auto d-block"
                        />
                    </Col>
                </Row>
                <Row className="justify-content-md-center">
                    <Col>
                        <p>{post.desc}</p>
                    </Col>
                </Row>

            </Container>

      </main>
    </div>
  )
}
