import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import createPost from '../utils/createPost'
import Button from 'react-bootstrap/Button'
import Form from 'react-bootstrap/Form'
import { useState }  from 'react'
import Layout from '../components/Layout'

export async function getStaticProps() {
  return {
    props: {
      cloudName: process.env.CLOUD_NAME,
      preset: process.env.PRESET,
    }
  };
}

export default function Home(props) {

  const [imgUrl, setImgUrl] = useState();
  const [postValues, setPostValues] = useState({title: "", desc: ""});

  function handleChange(e) {
    const {name, value} = e.target;
    setPostValues({...postValues, [name]: value});
    console.log(name, value);
  }

  function handleSubmit(e) {
    e.preventDefault();
    createPost(postValues, imgUrl);
    console.log("Created post with values: ", postValues.title, postValues.desc, imgUrl);
    setPostValues({title: "", desc: ""});
    setImgUrl(0);
  }

  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <script src="https://upload-widget.cloudinary.com/global/all.js" type="text/javascript"></script>
        <main className={styles.main}>
          <h1 className={styles.title}>
            Create a post below
          </h1>

          <div className={styles.grid}>
            <div 
              className={styles.card}
            >
              <Image
                src={imgUrl ? imgUrl : "/none.png"}
                alt="Uploaded Image"
                width="auto"
                height="auto"
              />
            </div>

            <Form onSubmit={handleSubmit}>
              <Form.Group>
                <Form.Label>Title</Form.Label>
                <Form.Control name="title" type="text" placeholder="Title" value={postValues.title}  onChange={handleChange} required />
              </Form.Group>

              <Form.Group controlId="desc">
                <Form.Label>Description</Form.Label>
                <Form.Control name="desc" as="textarea" placeholder="(Optional)" value={postValues.desc}  onChange={handleChange} />
              </Form.Group>

              <Form.Group>
                <br/>
                <Button
                  disabled={imgUrl ? true : false}
                  type="button"
                  size="sm"
                  variant={imgUrl ? "success" : "primary"}
                  onClick={() => {
                    var myWidget = cloudinary.createUploadWidget(
                      {
                      cloudName: props.cloudName, 
                      uploadPreset: props.preset
                      }, (error, result) => { 
                        if (!error && result && result.event === "success") { 
                          console.log('Done! Here is the image info: ', result.info); 
                          setImgUrl(result.info.secure_url);
                          myWidget.close();
                        }
                      }
                    )
                    myWidget.open();}}
                >
                  {imgUrl ? "Uploaded" : "Upload Image"}
                </Button>
              </Form.Group>
              <br/>
              <br/>
              <Button type="submit" size="lg" disabled={imgUrl ? false : true} >Create Post</Button>
            </Form>

          </div>

        </main>
      </div>
    </Layout>
  )
}
