import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import newPost from '../utils/newPost'
import { useState }  from 'react'

export async function getStaticProps() {
  return {
    props: {
      cloudName: process.env.CLOUD_NAME,
      preset: process.env.PRESET,
    }
  };
}

export default function Home(props) {

  const [imgUrl, setImgUrl] = useState();
  const [postValues, setPostValues] = useState({title: "", desc: ""});

  function handleChange(e) {
    const {name, value} = e.target;
    setPostValues({...postValues, [name]: value});
    console.log(name, value);
  }

  function handleSubmit(e) {
    e.preventDefault();
    newPost(postValues, imgUrl);
    console.log("Created post with values: ", postValues.title, postValues.desc, imgUrl);
    setPostValues({title: "", desc: ""});
    setImgUrl(0);
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <script src="https://upload-widget.cloudinary.com/global/all.js" type="text/javascript"></script>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="/">Our simple blog test!</a>
        </h1>

        <div className={styles.grid}>
          <div className={styles.card}>
            <Image
              src="/tomato.png"
              alt="Tomato"
              width={300}
              height={300}
            />
            <h3>Local Image</h3>
          </div>

          <div className={styles.card}>
            <Image
              src={imgUrl ? imgUrl : "/none.png"}
              alt="Uploaded Image"
              width={300}
              height={300}
            />
            <h3>Uploaded Image</h3>
          </div>

          <form onSubmit={handleSubmit}>
            <label>Title  </label>
            <input name="title" value={postValues.title} onChange={handleChange} required />
            <br/>
            <label>Description  </label>
            <input name="desc" value={postValues.desc} onChange={handleChange} />
            <br/>
            <label>Image  </label>
            <button
              type="button"
              onClick={() => {
                var myWidget = cloudinary.createUploadWidget(
                  {
                  cloudName: props.cloudName, 
                  uploadPreset: props.preset
                  }, (error, result) => { 
                    if (!error && result && result.event === "success") { 
                      console.log('Done! Here is the image info: ', result.info); 
                      setImgUrl(result.info.secure_url);
                    }
                  }
                )
                myWidget.open();}}
            >
              Upload Image
            </button>
            <br/>
            <button type="submit">Create Post</button>
          </form>

        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
