import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useState }  from 'react'

export async function getStaticProps() {

  return {
    props: {
      cloudName: process.env.CLOUD_NAME,
      preset: process.env.PRESET,
    }
  };
}

export default function Home(props) {

  const [imgUrl, setImgUrl] = useState("https://res.cloudinary.com/gaspacho/image/upload/v1621264935/sample.jpg")

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <script src="https://upload-widget.cloudinary.com/global/all.js" type="text/javascript"></script>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <div className={styles.card}>
            <Image
              src="/tomato.png"
              alt="Tomato"
              width={300}
              height={300}
              onClick={() => {
                var myWidget = cloudinary.createUploadWidget({
                  cloudName: props.cloudName, 
                  uploadPreset: props.preset}, (error, result) => { 
                    if (!error && result && result.event === "success") { 
                      console.log('Done! Here is the image info: ', result.info); 
                      setImgUrl(result.info.secure_url);
                    }
                  }
                )
                console.log(props.cloudName);
                myWidget.open();}}
            />
            <h3>Local Image</h3>
          </div>

          <div className={styles.card}>
            <Image
              src={imgUrl}
              alt="Cloudinary Image"
              width={300}
              height={300}
            />
            <h3>Cloudinary Image</h3>
          </div>

        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
