import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import delPost from '../utils/delPost'
import getAllPosts from '../utils/getAllPosts'
import Button from 'react-bootstrap/Button'

export async function getServerSideProps() {

  const posts = await getAllPosts();
  return {
    props: {
      posts: posts,
    }
  };
}

export default function Home(props) {
  const posts = props.posts;


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <script src="https://upload-widget.cloudinary.com/global/all.js" type="text/javascript"></script>
      <main className={styles.main}>
        <p><a href="/">&larr; Back</a></p>
        <h1 className={styles.title}>
          Posts list
        </h1>

        <div className={styles.grid}>
          {posts.map(({title, _id, imgUrl}) => (
              <div className={styles.card} key={_id}>
              <Image
                src={imgUrl}
                alt="Uploaded Image"
                width="auto"
                height="auto"
              />
              <h3>{title}</h3>
              <Button
                variant="danger"
                size='sm'
                onClick={() => delPost(_id)}
              >
                delete
              </Button>
            </div>
          ))}
        </div>

      </main>
    </div>
  )
}
